# Generated by Django 4.2.16 on 2024-12-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_alter_order_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Laptop', 'Laptop'), ('Mobile', 'Mobile'), ('Tablet', 'Tablet'), ('Headphones', 'Headphones'), ('Smartwatch', 'Smartwatch')], max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
    ]
